/**
 * ROZX Healthcare Platform — Health Records Feature Module
 */

// API
export {
    getHealthSummary,
    getFamilyMemberSummary,
    getDocuments,
    getDocument,
    uploadDocument,
    updateDocument,
    deleteDocument,
    getVitals,
    getVital,
    createVital,
    deleteVital,
    getVitalTrends,
    getMedications,
    getMedication,
    createMedication,
    updateMedication,
    deleteMedication,
    getMedicationReminders,
    takeMedicationAction,
    getAllergies,
    getAllergy,
    createAllergy,
    updateAllergy,
    deleteAllergy,
    getHealthFamilyMembers,
    getHealthFamilyMember,
    createHealthFamilyMember,
    updateHealthFamilyMember,
    deleteHealthFamilyMember,
} from './api/health-records-api';

// Hooks
export {
    healthKeys,
    useHealthSummary,
    useFamilyMemberSummary,
    useDocuments,
    useDocument,
    useUploadDocument,
    useUpdateDocument,
    useDeleteDocument,
    useVitals,
    useVital,
    useCreateVital,
    useDeleteVital,
    useVitalTrends,
    useMedications,
    useMedication,
    useCreateMedication,
    useUpdateMedication,
    useDeleteMedication,
    useMedicationReminders,
    useTakeMedicationAction,
    useAllergies,
    useAllergy,
    useCreateAllergy,
    useUpdateAllergy,
    useDeleteAllergy,
    useHealthFamilyMembers,
    useCreateHealthFamilyMember,
    useUpdateHealthFamilyMember,
    useDeleteHealthFamilyMember,
} from './hooks/use-health-records';
